name: deploy expo
on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths: 
      - expo/**

jobs:
  deploy-expo-web:
    name: deploy expo web
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    defaults:
      run:
        working-directory: ./expo

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: expo/package-lock.json

      - name: install dependencies (includes netlify as dev dependency)
        run: npm ci

      - name: build project
        run: npx expo export -p web

      - name: deploy to netlify
        run: |
          netlify deploy \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }} \
            --prod

