name: test node
on:
  push:
    branches:
      - dev
    paths: 
      - node/**

jobs:
  test-node:
    name: test node server
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./node

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: node/package-lock.json

      - name: install dependencies
        run: npm ci

      - name: run pretest and test scripts
        run: |
          npm run db:test:restart
          npm run test
