name: test
on:
  push:
    branches:
      - dev

jobs:
  test-node:
    name: test node server
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./node

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules 
          key: node-server-test-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: install dependencies
        run: npm ci

      - name: run pretest and test scripts
        run: |
          npm run db:test:restart
          npm run test
